server-version: "1.0"
debug: false
bind-address: "0.0.0.0"
port: 50069
index-page: "index.html"
persistence:
  use-persistent-connections: false
  persistent-connection-timeout: 6000
files:
  root-dir: "."
logging:
  enabled: true
  log-file-path: "./http-log"