server-version: "1.0"
debug: false
bind-address: "0.0.0.0"
port: 50069
index-page: "index.html"
persistence:
  use-persistent-connections: false
  persistent-connection-timeout: 6000
files:
  root-dir: "."
logging:
  enabled: true
  http-log-file-path: "."
  http-log-file-name: "http_log"
  http-log-file-max-length: 150
  error-log-file-path: "."
  error-log-file-name: "error_log"
  error-log-file-max-length: 150
  error-log-minlevel: WARN    #Options: DEBUG, VERBOSE, INFO, WARN (default), SEVERE, FATAL