server-version: "1.1"
debug: true
bind-address: "0.0.0.0"
port: 50069
persistence:
  use-persistent-connections: false
  persistent-connection-timeout: 6000
files:
  root-dir: "."
logging:
  enabled: true
  log-file-path: "./http-log"